sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - cd tim05/tim05
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=true -B

dist: trusty

deploy:
  provider: heroku
  api_key: 71bab1b3-3025-462f-9ba5-8b60537340c7
  app: eclinic05