sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - cd tim05/tim05
  - chmod +x mvnw
  
addons:
    sonarcloud:
    organization: "mrsisa05"
    token: "76b1154d1c99218978e06dbdf77d657cb88fb202" # encrypted value of your token

 
script:
  - ./mvnw clean install -DskipTests=true -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=tim05 -Dsonar.organization=romana98-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=76b1154d1c99218978e06dbdf77d657cb88fb202

dist: trusty

deploy:
  provider: heroku
  api_key: 71bab1b3-3025-462f-9ba5-8b60537340c7
  app: eclinic05