sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - cd tim05/tim05
  - chmod +x mvnw
  
addons:
    sonarcloud:
    organization: "mrsisa05"
    token: "917f6268e9c19155fd1d85b113465112be6c27a7" # encrypted value of your token

 
script:
  - ./mvnw clean install -DskipTests=true -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=tim05 -Dsonar.organization=mrsisa05 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=917f6268e9c19155fd1d85b113465112be6c27a7

dist: trusty

deploy:
  provider: heroku
  api_key: 71bab1b3-3025-462f-9ba5-8b60537340c7
  app: eclinic05